# Generated by Django 5.1.1 on 2024-11-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="User",
            new_name="new_field_name",
        ),
    ]
